/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ResultadoTO;
import dao.ResultadoDao;
import dao.ResultadoDaoI;
import java.awt.Component;
import dao.*;
import java.awt.List;
import javax.swing.JTextField;

/**
 *
 * @author HP
 */
public class JuegoDe3EnRaya extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form JuegoDe3EnRaya
     */
    String trn = "X";
    JButton vtn[] = new JButton[9];

    int vs[][] = {
        {1, 2, 3},
        {4, 5, 6},
        {7, 8, 9},
        {1, 4, 7},
        {2, 5, 8},
        {3, 6, 9},
        {1, 5, 9},
        {3, 5, 7}

    };

    DefaultTableModel model;

    public JuegoDe3EnRaya() {
        initComponents();
        
        jTextField_nombre_partida.setVisible(false);
        jTextField_turno.setEditable(false);
        jTextField_Jugador1Puntaje.setEditable(false);
        jTextField_Jugador2Puntaje.setEditable(false);
        jButton_continuar.setVisible(false);
        jButton_reiniciar.setVisible(false);
        jButton_terminar.setVisible(false);
        
        
        tabladepuntajes();
        vtn[0] = jButton1T;
        vtn[1] = jButton2T;
        vtn[2] = jButton3T;
        vtn[3] = jButton4T;
        vtn[4] = jButton5T;
        vtn[5] = jButton6T;
        vtn[6] = jButton7T;
        vtn[7] = jButton8T;
        vtn[8] = jButton9T;

        jButton1T.setBackground(Color.white);
        jButton2T.setBackground(Color.white);
        jButton3T.setBackground(Color.white);
        jButton4T.setBackground(Color.white);
        jButton5T.setBackground(Color.white);
        jButton6T.setBackground(Color.white);
        jButton7T.setBackground(Color.white);
        jButton8T.setBackground(Color.white);
        jButton9T.setBackground(Color.white);

        rDao = new ResultadoDao();
        rDao.listarResultados();

        ListaClientes();

    }

    ResultadoDaoI rd = new ResultadoDao();
    ResultadoDaoI rDao;

    public void tabladepuntajes() {

        model = new DefaultTableModel();
        model.addColumn("Nombre Partido");
        model.addColumn("Nombre Jugador 1");
        model.addColumn("Nombre Jugador 2");
        model.addColumn("Nombre Ganador");
        model.addColumn("Puntuacion");
        model.addColumn("Estado");

        TablaDeRegistroDePuntajes.setModel(model);

    }

    

    public void ListaClientes() {
        rDao = new ResultadoDao();

        java.util.List<ResultadoTO> listarResultados = rDao.listarResultados();
        TablaDeRegistroDePuntajes.setAutoCreateRowSorter(true);
        model = (DefaultTableModel) TablaDeRegistroDePuntajes.getModel();
        Object[] ob = new Object[7];
        for (int i = 0; i < listarResultados.size(); i++) {
            ob[0] = listarResultados.get(i).getNombre_partida();
            ob[1] = listarResultados.get(i).getNombre_jugador1();
            ob[2] = listarResultados.get(i).getNombre_jugador2();
            ob[3] = listarResultados.get(i).getGanador();
            ob[4] = listarResultados.get(i).getPunto();
            ob[5] = listarResultados.get(i).getEstado();
            model.addRow(ob);
        }
        TablaDeRegistroDePuntajes.setModel(model);
    }

    private void limpiarTablaClientes() {
        for (int i = 0; i < TablaDeRegistroDePuntajes.getRowCount(); i++) {
            model.removeRow(i);
            i -= 1;
        }
        TablaDeRegistroDePuntajes.setModel(model);
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3T = new javax.swing.JButton();
        jButton2T = new javax.swing.JButton();
        jButton1T = new javax.swing.JButton();
        jButton4T = new javax.swing.JButton();
        jButton6T = new javax.swing.JButton();
        jButton7T = new javax.swing.JButton();
        jButton8T = new javax.swing.JButton();
        jButton9T = new javax.swing.JButton();
        jButton5T = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_turno = new javax.swing.JTextField();
        jTextField_Jugador1Puntaje = new javax.swing.JTextField();
        jTextField_Jugador2Puntaje = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_nombreJugador1 = new javax.swing.JTextField();
        jTextField_nombreJugador2 = new javax.swing.JTextField();
        jButton_Iniciar = new javax.swing.JButton();
        jButton_Anular = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDeRegistroDePuntajes = new javax.swing.JTable();
        jButton_continuar = new javax.swing.JButton();
        jButton_terminar = new javax.swing.JButton();
        jButton_reiniciar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextField_nombre_partida = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        jButton3T.setFont(new java.awt.Font("Ink Free", 1, 36)); // NOI18N
        jButton3T.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3TMousePressed(evt);
            }
        });
        jButton3T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3TActionPerformed(evt);
            }
        });

        jButton2T.setFont(new java.awt.Font("Ink Free", 1, 36)); // NOI18N
        jButton2T.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2TMousePressed(evt);
            }
        });
        jButton2T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2TActionPerformed(evt);
            }
        });

        jButton1T.setFont(new java.awt.Font("Ink Free", 1, 36)); // NOI18N
        jButton1T.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1TMousePressed(evt);
            }
        });
        jButton1T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1TActionPerformed(evt);
            }
        });

        jButton4T.setFont(new java.awt.Font("Ink Free", 1, 36)); // NOI18N
        jButton4T.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton4TMousePressed(evt);
            }
        });

        jButton6T.setFont(new java.awt.Font("Ink Free", 1, 36)); // NOI18N
        jButton6T.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton6TMousePressed(evt);
            }
        });
        jButton6T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6TActionPerformed(evt);
            }
        });

        jButton7T.setFont(new java.awt.Font("Ink Free", 1, 36)); // NOI18N
        jButton7T.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton7TMousePressed(evt);
            }
        });
        jButton7T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7TActionPerformed(evt);
            }
        });

        jButton8T.setFont(new java.awt.Font("Ink Free", 1, 36)); // NOI18N
        jButton8T.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton8TMousePressed(evt);
            }
        });
        jButton8T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8TActionPerformed(evt);
            }
        });

        jButton9T.setFont(new java.awt.Font("Ink Free", 1, 36)); // NOI18N
        jButton9T.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton9TMousePressed(evt);
            }
        });
        jButton9T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9TActionPerformed(evt);
            }
        });

        jButton5T.setFont(new java.awt.Font("Ink Free", 1, 36)); // NOI18N
        jButton5T.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton5TMousePressed(evt);
            }
        });
        jButton5T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5TActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel4.setText("Turno:");

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel5.setText("Jugador 1:");

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel6.setText("Jugador 2:");

        jTextField_turno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_turnoActionPerformed(evt);
            }
        });

        jTextField_Jugador1Puntaje.setText("0");
        jTextField_Jugador1Puntaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Jugador1PuntajeActionPerformed(evt);
            }
        });

        jTextField_Jugador2Puntaje.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4T, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1T, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7T, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2T, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3T, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton8T, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton5T, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton9T, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton6T, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(54, 54, 54))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jTextField_Jugador1Puntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField_Jugador2Puntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jTextField_turno, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1T, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2T, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton3T, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4T, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5T, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6T, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7T, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8T, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9T, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_turno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Jugador1Puntaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Jugador2Puntaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Script MT Bold", 1, 64)); // NOI18N
        jLabel1.setText("Tres en Raya");

        jLabel2.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
        jLabel3.setText("Andrés Lino Montes Mamani");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 204));

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombre del Jugador 1:");

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nombre del Jugador 2:");

        jTextField_nombreJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nombreJugador1ActionPerformed(evt);
            }
        });

        jTextField_nombreJugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nombreJugador2ActionPerformed(evt);
            }
        });

        jButton_Iniciar.setBackground(new java.awt.Color(0, 204, 255));
        jButton_Iniciar.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        jButton_Iniciar.setText("Iniciar");
        jButton_Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IniciarActionPerformed(evt);
            }
        });

        jButton_Anular.setBackground(new java.awt.Color(51, 204, 255));
        jButton_Anular.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        jButton_Anular.setText("Anular");
        jButton_Anular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AnularActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 153, 255));

        jLabel9.setFont(new java.awt.Font("Snap ITC", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 255, 255));
        jLabel9.setText("Tabla de Puntajes:");

        TablaDeRegistroDePuntajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre Partido", "Nombre Jugador 1", "Nombre Jugador 2", "Nombre Ganador", "Puntuacion", "Estado"
            }
        ));
        TablaDeRegistroDePuntajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDeRegistroDePuntajesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaDeRegistroDePuntajes);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1021, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton_continuar.setBackground(new java.awt.Color(0, 204, 255));
        jButton_continuar.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        jButton_continuar.setText("Continuar");
        jButton_continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_continuarActionPerformed(evt);
            }
        });

        jButton_terminar.setBackground(new java.awt.Color(0, 204, 255));
        jButton_terminar.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        jButton_terminar.setText("Terminar");
        jButton_terminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_terminarActionPerformed(evt);
            }
        });

        jButton_reiniciar.setBackground(new java.awt.Color(0, 204, 255));
        jButton_reiniciar.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        jButton_reiniciar.setText("Reiniciar Partida");
        jButton_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_reiniciarActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jButton1.setText("Borrar Partida");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Seleccione la fila a borrar:");

        jTextField_nombre_partida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nombre_partidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(30, 30, 30)
                            .addComponent(jTextField_nombreJugador2))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(30, 30, 30)
                            .addComponent(jTextField_nombreJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton_Iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jButton_Anular, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jButton_continuar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_reiniciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_terminar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(29, 29, 29)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jTextField_nombre_partida, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_nombreJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_nombre_partida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_nombreJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_Iniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_Anular, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                        .addComponent(jButton_continuar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_reiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_terminar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1057, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3TActionPerformed

    }//GEN-LAST:event_jButton3TActionPerformed

    private void jButton2TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2TActionPerformed

    }//GEN-LAST:event_jButton2TActionPerformed

    private void jButton6TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6TActionPerformed

    }//GEN-LAST:event_jButton6TActionPerformed

    private void jButton7TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7TActionPerformed

    }//GEN-LAST:event_jButton7TActionPerformed

    private void jButton8TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8TActionPerformed

    }//GEN-LAST:event_jButton8TActionPerformed

    private void jButton9TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9TActionPerformed

    }//GEN-LAST:event_jButton9TActionPerformed

    private void jButton5TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5TActionPerformed

    }//GEN-LAST:event_jButton5TActionPerformed

    private void jTextField_nombreJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nombreJugador1ActionPerformed

    }//GEN-LAST:event_jTextField_nombreJugador1ActionPerformed

    private void jTextField_nombreJugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nombreJugador2ActionPerformed

    }//GEN-LAST:event_jTextField_nombreJugador2ActionPerformed

    private void jTextField_turnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_turnoActionPerformed

    }//GEN-LAST:event_jTextField_turnoActionPerformed

    private void jTextField_Jugador1PuntajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Jugador1PuntajeActionPerformed

    }//GEN-LAST:event_jTextField_Jugador1PuntajeActionPerformed

    private void jButton1TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1TActionPerformed

    }//GEN-LAST:event_jButton1TActionPerformed

    String permisoInicio = "";

    private void jButton1TMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1TMousePressed

        if (permisoInicio.equals("SI")) {
            presionar(1);
        }


    }//GEN-LAST:event_jButton1TMousePressed

    private void jButton2TMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2TMousePressed
        if (permisoInicio.equals("SI")) {
            presionar(2);
        }
    }//GEN-LAST:event_jButton2TMousePressed

    private void jButton3TMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3TMousePressed
        if (permisoInicio.equals("SI")) {
            presionar(3);
        }
    }//GEN-LAST:event_jButton3TMousePressed

    private void jButton4TMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4TMousePressed
        if (permisoInicio.equals("SI")) {
            presionar(4);
        }
    }//GEN-LAST:event_jButton4TMousePressed

    private void jButton5TMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5TMousePressed
        if (permisoInicio.equals("SI")) {
            presionar(5);
        }
    }//GEN-LAST:event_jButton5TMousePressed

    private void jButton6TMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6TMousePressed
        if (permisoInicio.equals("SI")) {
            presionar(6);
        }
    }//GEN-LAST:event_jButton6TMousePressed

    private void jButton7TMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7TMousePressed
        if (permisoInicio.equals("SI")) {
            presionar(7);
        }
    }//GEN-LAST:event_jButton7TMousePressed

    private void jButton8TMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8TMousePressed
        if (permisoInicio.equals("SI")) {
            presionar(8);
        }
    }//GEN-LAST:event_jButton8TMousePressed

    private void jButton9TMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9TMousePressed
        if (permisoInicio.equals("SI")) {
            presionar(9);
        }
    }//GEN-LAST:event_jButton9TMousePressed

    private void jButton_AnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AnularActionPerformed
        
        jButton_continuar.setVisible(false);
        jButton_reiniciar.setVisible(false);
        jButton_terminar.setVisible(false);
        
        ocultarCuadros();

        permisoInicio = "NO";

        jButton_Iniciar.setVisible(true);

        limpiarjtextfields();

        jTextField_nombreJugador1.setEditable(true);
        jTextField_nombreJugador2.setEditable(true);
        
        
        
        JOptionPane.showMessageDialog(rootPane, "Vaya... no seria mala idea comenzar otra partida :/");
        
        
        
        ResultadoTO res = new ResultadoTO();
        ResultadoDaoI re = new ResultadoDao();
        
        res.setGanador("Anulado");
        res.setPunto(0);
        res.setEstado("Anulado");
        
        java.util.List<ResultadoTO> listarResultados = rDao.listarResultados();
            //Tener un row [FILA] ya establecida en la base de datos porque el listarResultados.size no tendra un tamaño
            for (int i = 0; i < listarResultados.size(); i++) {
                res.setNombre_partida("Partida " + i);
                
            }
        
            
        
        
        re.actualizarResultados(res);
        
        limpiarTablaClientes();
            ListaClientes();
        
        JOptionPane.showMessageDialog(rootPane, "Se anulo y registro en la tabla de puntuaciones satisfactoriamente");
        
    }//GEN-LAST:event_jButton_AnularActionPerformed

    public void limpiarjtextfields() {

        jTextField_nombreJugador1.setText("");
        jTextField_nombreJugador2.setText("");
        jTextField_turno.setText("");
        jTextField_Jugador1Puntaje.setText("");
        jTextField_Jugador2Puntaje.setText("");

    }

    public void ocultarCuadros() {

        jButton1T.setText("");
        jButton2T.setText("");
        jButton3T.setText("");
        jButton4T.setText("");
        jButton5T.setText("");
        jButton6T.setText("");
        jButton7T.setText("");
        jButton8T.setText("");
        jButton9T.setText("");

        jButton1T.setBackground(Color.white);
        jButton2T.setBackground(Color.white);
        jButton3T.setBackground(Color.white);
        jButton4T.setBackground(Color.white);
        jButton5T.setBackground(Color.white);
        jButton6T.setBackground(Color.white);
        jButton7T.setBackground(Color.white);
        jButton8T.setBackground(Color.white);
        jButton9T.setBackground(Color.white);

    }


    private void jButton_IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_IniciarActionPerformed

        
        
        if (jTextField_nombreJugador1.getText().equals("")
                || jTextField_nombreJugador2.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Ingrese los datos completos");

        } else {

            jButton_continuar.setVisible(true);
            jButton_reiniciar.setVisible(true);
            jButton_terminar.setVisible(true);
            
             jTextField_turno.setText(jTextField_nombreJugador1.getText());
            
            ResultadoTO res = new ResultadoTO();
            ResultadoDaoI re = new ResultadoDao();

            res.setNombre_jugador1(jTextField_nombreJugador1.getText());
            res.setNombre_jugador2(jTextField_nombreJugador2.getText());

            java.util.List<ResultadoTO> listarResultados = rDao.listarResultados();
            //Tener un row [FILA] ya establecida en la base de datos porque el listarResultados.size no tendra un tamaño
            for (int i = 0; i < listarResultados.size(); i++) {
                res.setNombre_partida("Partida " + (i + 1));
            }

            re.crearResultados(res);
            limpiarTablaClientes();
            ListaClientes();
            //capturarJugador();
            permisoInicio = "SI";
            jButton_Iniciar.setVisible(false);
            
            jTextField_nombreJugador1.setEditable(false);
            jTextField_nombreJugador2.setEditable(false);
            JOptionPane.showMessageDialog(null, "Se registro de manera satisfactoria ¡¡Que comienze el juego!!");
        }

    }//GEN-LAST:event_jButton_IniciarActionPerformed

    private void jButton_continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_continuarActionPerformed
        
        ocultarCuadros();
    }//GEN-LAST:event_jButton_continuarActionPerformed

    private void jButton_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_reiniciarActionPerformed
        jTextField_turno.setText(jTextField_nombreJugador1.getText());
        jTextField_Jugador1Puntaje.setText("0");
        jTextField_Jugador2Puntaje.setText("0");
    }//GEN-LAST:event_jButton_reiniciarActionPerformed

    private void jButton_terminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_terminarActionPerformed
        
        permisoInicio = "NO";
        ocultarCuadros();
        jButton_Iniciar.setVisible(true);
        jButton_continuar.setVisible(false);
        jButton_reiniciar.setVisible(false);
        jButton_terminar.setVisible(false);
        jTextField_nombreJugador1.setEditable(true);
        jTextField_nombreJugador2.setEditable(true);
        
    int puntajFinal1 = Integer.parseInt(jTextField_Jugador1Puntaje.getText());
    int puntajFinal2 = Integer.parseInt(jTextField_Jugador2Puntaje.getText());
    
        if(puntajFinal1>puntajFinal2){
        JOptionPane.showMessageDialog(rootPane, "Felicidades "+"''"+jTextField_nombreJugador1.getText()+"''"+" eres el mejor :)");
        
        String ganador= jTextField_nombreJugador1.getText();
        
        ResultadoTO res = new ResultadoTO();
        ResultadoDaoI re = new ResultadoDao();
        
        res.setGanador(ganador+" Ganador");
        res.setPunto(puntajFinal1 /* "Puntaje jugador 1: "+ puntajFinal1 + " Puntaje jugador 2: "+ puntajFinal2*/);
        res.setEstado("Terminado");
        
        java.util.List<ResultadoTO> listarResultados = rDao.listarResultados();
            //Tener un row [FILA] ya establecida en la base de datos porque el listarResultados.size no tendra un tamaño
            for (int i = 0; i < listarResultados.size(); i++) {
                res.setNombre_partida("Partida " + i);
                
            }
        
            
        
        
        re.actualizarResultados(res);
        
        limpiarTablaClientes();
            ListaClientes();
        
        JOptionPane.showMessageDialog(rootPane, "Se registro en la tabla de puntuaciones satisfactoriamente");
        }else if(puntajFinal1<puntajFinal2){
        JOptionPane.showMessageDialog(rootPane, "Felicidades "+"''"+jTextField_nombreJugador2.getText()+"''"+" eres el mejor :)");
        
        String ganador= jTextField_nombreJugador2.getText();
        
        ResultadoTO res2 = new ResultadoTO();
            ResultadoDaoI re2 = new ResultadoDao();
        
            
        res2.setGanador(ganador+" Ganador");
        res2.setPunto(puntajFinal2 /* "Puntaje jugador 1: "+ puntajFinal1 + " Puntaje jugador 2: "+ puntajFinal2*/);
        res2.setEstado("Terminado");
        
        java.util.List<ResultadoTO> listarResultados = rDao.listarResultados();
            //Tener un row [FILA] ya establecida en la base de datos porque el listarResultados.size no tendra un tamaño
            for (int i = 0; i < listarResultados.size(); i++) {
                res2.setNombre_partida("Partida " + i);
                
            }
        
            
        
        
        re2.actualizarResultados(res2);
        
            
        limpiarTablaClientes();
            ListaClientes();
        
        JOptionPane.showMessageDialog(rootPane, "Se registro en la tabla de puntuaciones satisfactoriamente");
        }else if(puntajFinal1 == puntajFinal2){
        JOptionPane.showMessageDialog(rootPane, "Felicidades "+"''"+jTextField_nombreJugador1.getText()+"''"+" y "+"''"+jTextField_nombreJugador2.getText()+"''"+" son los mejores :)");
            
        String ganador= "Empate";
        
        ResultadoTO res3 = new ResultadoTO();
            ResultadoDaoI re3 = new ResultadoDao();
            
            
            
            
        res3.setGanador(ganador);
        res3.setPunto(puntajFinal1 /* "Puntaje jugador 1: "+ puntajFinal1 + " Puntaje jugador 2: "+ puntajFinal2*/);
        res3.setEstado("Terminado");
        
        java.util.List<ResultadoTO> listarResultados = rDao.listarResultados();
            //Tener un row [FILA] ya establecida en la base de datos porque el listarResultados.size no tendra un tamaño
            for (int i = 0; i < listarResultados.size(); i++) {
                res3.setNombre_partida("Partida " + i);
                
            }
        
            
        
        
        re3.actualizarResultados(res3);
        
            
            
        limpiarTablaClientes();
            ListaClientes();
        
        JOptionPane.showMessageDialog(rootPane, "Se registro en la tabla de puntuaciones satisfactoriamente");
                }
        
        
    }//GEN-LAST:event_jButton_terminarActionPerformed

    private void jTextField_nombre_partidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nombre_partidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nombre_partidaActionPerformed

    private void TablaDeRegistroDePuntajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDeRegistroDePuntajesMouseClicked
        int row = 0;
        row=TablaDeRegistroDePuntajes.getSelectedRow();
        
        jTextField_nombre_partida.setText(TablaDeRegistroDePuntajes.getValueAt(row, 0).toString());
        
    }//GEN-LAST:event_TablaDeRegistroDePuntajesMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      if(jTextField_nombre_partida.getText().equals("")){
        
            JOptionPane.showMessageDialog(null, "¡Seleccione la fila a eliminar!");
            
        }else{
            
        ResultadoTO res = new ResultadoTO();
        ResultadoDaoI re = new ResultadoDao();
        res.setNombre_partida(jTextField_nombre_partida.getText());
        
        re.eliminarResultados(res);
        
         limpiarTablaClientes();
            ListaClientes();
        
        JOptionPane.showMessageDialog(null, "Se Elimino de manera satisfactoria");
        
         
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public ResultadoTO capturarJugador() {
        ResultadoTO res = new ResultadoTO();

        res.setNombre_jugador1(jTextField_nombreJugador1.getText());
        res.setNombre_jugador2(jTextField_nombreJugador2.getText());

        ResultadoDaoI re = new ResultadoDao();
        re.crearResultados(res);

        return res;
    }

    public void presionar(int casilla) {
        if (vtn[casilla - 1].getText().equals("")) {

            vtn[casilla - 1].setText(trn);
            cambiarturno();
            comprobarganador();

        }

    }

    public void cambiarturno() {
        if (trn.equals("X")) {
            trn = "0";
            jTextField_turno.setText(jTextField_nombreJugador2.getText());
        } else {
            trn = "X";
            jTextField_turno.setText(jTextField_nombreJugador1.getText());
        }

    }

    
    
    public void puntajePorCadaJugador(){
    
       
      
       
               
        
    }
    
    public void suma1(){
    int puntaj1 = Integer.parseInt(jTextField_Jugador1Puntaje.getText());
    int sum1= puntaj1+1;
    jTextField_Jugador1Puntaje.setText(""+sum1);
    }
    
    public void suma2 (){
    int puntaj2 = Integer.parseInt(jTextField_Jugador2Puntaje.getText());
    int sum2= puntaj2+1;
    jTextField_Jugador2Puntaje.setText(""+sum2);
    
    }
    
    public void comprobarganador() {
        for (int i = 0; i < vs.length; i++) {
            if (vtn[vs[i][0] - 1].getText().equals("X")
                    && vtn[vs[i][1] - 1].getText().equals("X")
                    && vtn[vs[i][2] - 1].getText().equals("X")) {

                vtn[vs[i][0] - 1].setBackground(Color.green);
                vtn[vs[i][1] - 1].setBackground(Color.green);
                vtn[vs[i][2] - 1].setBackground(Color.green);

                System.out.println();
                JOptionPane.showMessageDialog(rootPane, "Excelente Jugada "+"''"+jTextField_nombreJugador1.getText()+"''");
                suma1();
                
                ocultarCuadros();
            }

            if (vtn[vs[i][0] - 1].getText().equals("0")
                    && vtn[vs[i][1] - 1].getText().equals("0")
                    && vtn[vs[i][2] - 1].getText().equals("0")) {

                vtn[vs[i][0] - 1].setBackground(Color.green);
                vtn[vs[i][1] - 1].setBackground(Color.green);
                vtn[vs[i][2] - 1].setBackground(Color.green);

                System.out.println();
                JOptionPane.showMessageDialog(rootPane, "Excelente Jugada "+"''"+jTextField_nombreJugador2.getText()+"''");
                suma2();
                
                ocultarCuadros();
                
            }

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegoDe3EnRaya().setVisible(true);
            }

        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaDeRegistroDePuntajes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1T;
    private javax.swing.JButton jButton2T;
    private javax.swing.JButton jButton3T;
    private javax.swing.JButton jButton4T;
    private javax.swing.JButton jButton5T;
    private javax.swing.JButton jButton6T;
    private javax.swing.JButton jButton7T;
    private javax.swing.JButton jButton8T;
    private javax.swing.JButton jButton9T;
    private javax.swing.JButton jButton_Anular;
    private javax.swing.JButton jButton_Iniciar;
    private javax.swing.JButton jButton_continuar;
    private javax.swing.JButton jButton_reiniciar;
    private javax.swing.JButton jButton_terminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField_Jugador1Puntaje;
    private javax.swing.JTextField jTextField_Jugador2Puntaje;
    private javax.swing.JTextField jTextField_nombreJugador1;
    private javax.swing.JTextField jTextField_nombreJugador2;
    private javax.swing.JTextField jTextField_nombre_partida;
    private javax.swing.JTextField jTextField_turno;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
